attrib -s -h Pikachu.txt
attrib -s -h Pikachu.txt
attrib -s -h Pikachu.txt
attrib -s -h Pikachu.txt
attrib -s -h Pikachu.txt
attrib -s -h Pikachu.txt
attrib -s -h Pikachu.txt
attrib -s -h Pikachu.txt
attrib -s -h Pikachu.txt
